- docs/CONTRIBUTING.md
- docs/SECURITY.md
Updating the docs to remove some non-inclusive language.
| Issue ID |
| -------- |
|  #64     |
Doc changes only
> Bugfix non inclusive language

- README.md
This PR ensures The latest version badge on the root README.md file is being rendered correctly..
| Issue ID |
| -------- |
|      #67     |
> Ensures the latest version badge is rendered correctly

- README.md
- docs/GETTING_STARTED_GUIDE.md
Update README and GETTING STARTED GUIDE to indicate that CSI Driver for PowerFlex is required for Karavi Metrics PowerFlex
| Issue ID |
| -------- |
|    #69       |
> CSI Driver for PowerFlex is required for Karavi Metrics PowerFlex

- .github/ISSUE_TEMPLATE/bug_report.md
Update the bug report template to include all the system information details.
| Issue ID |
| -------- |
| #66 |
N/A
> Update bug report template for system information details

- docs/GETTING_STARTED_GUIDE.md
Add Openshift supported versions
| Issue ID |
| -------- |
|    https://github.com/dell/helm-charts/issues/54    |
> Add Openshift supported versions

- internal/service/testdata/config-missing-endpoint.json
- internal/service/testdata/config-missing-password.json
- internal/service/testdata/config-missing-systemid.json
- internal/service/testdata/config-missing-username.json
- internal/service/testdata/config-with-default.json
- internal/service/testdata/config-with-invalid-default-system.json
- internal/service/testdata/config-with-no-default.json
Use fake hostnames instead of fake IP addresses for tests.
| Issue ID |
| -------- |
|      #90     |
> Use fake hostnames instead of fake IP addresses for tests

- README.md
Updated the supported k8s versions
| Issue ID |
| -------- |
|    https://github.com/dell/karavi-observability/issues/28      |
> Update supported k8s versions

- .github/workflows/actions.yml
- Makefile
Updated Makefile to changed image name to use 'csm' for "Container Storage Modules" instead of 'karavi' to align with new Docker Hub repository names
| Issue ID |
| -------- |
|          |
> Updated Makefile to tag and push new image names

- go.mod
- go.sum
Updated the crypto library due to a CVE during image scan.
| Issue ID |
| -------- |
|    https://github.com/dell/karavi-observability/issues/64      |
> Updated crypto library due to CVE

- internal/k8s/volume_finder.go
- internal/k8s/volume_finder_test.go
A few sentences describing the overall goals of the pull request's commits.
| Issue ID |
| -------- |
|   [issue-63](https://github.com/dell/karavi-observability/issues/63)       |
- tested on cluster with PVs without CSI field
> BUGXIX-63 - do not fail when PVs without CSI exists

- go.mod
- go.sum
Update to latest goscaleio version in go.mod
|N/A |
> Update released go clients for supported platforms

- go.mod
- go.sum
Updated goscaleio client
| https://github.com/dell/csm/issues/117  |
> Updated goscaleio client

- .github/pull_request_template.md
A few sentences describing the overall goals of the pull request's commits.
|https://github.com/dell/csm/issues/279 |
> Adding UI check to PR template

- go.mod
- go.sum
This PR merges the patch dependency version to conform with baseline v1.1.0 release
|https://github.com/dell/csm/issues/288|
Unit tests, manual UI verification
> Update 3rd party dependencies

- go.mod
- go.sum
- internal/service/service.go
- internal/service/service_test.go
Update goscaleio
| https://github.com/dell/csm/issues/243|
> Update go client 

- go.mod
- internal/service/configuration_reader.go
A few sentences describing the overall goals of the pull request's commits.
|https://github.com/dell/csm/issues/916|
> Remove dependence on io/ioutil, update Go to 1.21

- .gitignore
- .golangci.yaml
- Dockerfile
- Makefile
- README.md
Implementation of multistage docker build for Powerflex metrics
| https://github.com/dell/csm/issues/1098 |
> Multistage image build for powerflex metrics

- Dockerfile
- licenses/LICENSE
Update licenses directory with LICENSE file for openshift-preflight scan fix
| |
> Update licenses directory with LICENSE file for openshift-preflight scan fix

- Makefile
Replace docker build with podman build
| https://github.com/dell/csm/issues/1435 |
> Replace docker build with podman build

- go.mod
- go.sum
update goscaleio module
| https://github.com/dell/csm/issues/1435 |
> update goscaleio module

- Makefile
This PR adds Makefile targets to run GitHub Actions checks locally:
`actions` Target :
Runs all pull request checks with enhanced logging.
`action-help` Target :
Displays instructions for running specific workflows with act.
Usage:
Run all PR checks: `make actions`
Get workflow instructions: `make action-help`
Enhances local testing and debugging of GitHub Actions.
| https://github.com/dell/csm/issues/1490|
> karavi-metrics-powerflex/Add Makefile Targets for Local PR Checks

- .github/workflows/release.yaml
Fixed patch release
|https://github.com/dell/csm/issues/1490 |
Tested for driver with fork (normal release): https://github.com/harishp8889/test-powerstore-automation/actions/runs/14374648455/job/40304179725
> Fixed patch release

- README.md
Update Golang and k8s version
| https://github.com/dell/csm/issues/1896 |
> Update Golang and k8s version
